package com.insurance.claim.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Claim Entity — Central business entity of the entire system.
 *
 * CLAIM LIFECYCLE (state machine):
 *
 *  SUBMITTED ──► UNDER_REVIEW ──► APPROVED ──► SETTLED
 *                     │
 *                     └──────────► REJECTED
 *                     │
 *                     └──────────► PENDING_INFO  (agent needs more docs)
 *                                       │
 *                                       └──► UNDER_REVIEW (resubmitted)
 *
 * Each transition:
 *  - Is persisted in ClaimStatusHistory
 *  - Publishes a Kafka event (claim.status.changed)
 *  - Triggers notifications via notification-service (via Kafka)
 */
@Entity
@Table(name = "claims", indexes = {
    @Index(name = "idx_claim_number",      columnList = "claim_number",  unique = true),
    @Index(name = "idx_claim_customer_id", columnList = "customer_id"),
    @Index(name = "idx_claim_status",      columnList = "status"),
    @Index(name = "idx_claim_policy_number", columnList = "policy_number"),
    @Index(name = "idx_claim_incident_date", columnList = "incident_date")
})
@Getter @Setter @NoArgsConstructor @AllArgsConstructor
@Builder
public class Claim {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable claim number (e.g., CLM-2024-000042).
     * Generated by the service on creation — not sequential to avoid enumeration.
     */
    @Column(name = "claim_number", nullable = false, unique = true, length = 30)
    private String claimNumber;

    // ── Parties ───────────────────────────────────────────────────────────────

    /** ID from auth-service / user-service — the customer filing the claim */
    @Column(name = "customer_id", nullable = false)
    private Long customerId;

    /** ID of the agent currently handling this claim (nullable — unassigned initially) */
    @Column(name = "assigned_agent_id")
    private Long assignedAgentId;

    // ── Claim details ─────────────────────────────────────────────────────────

    @Column(name = "policy_number", nullable = false, length = 50)
    private String policyNumber;

    @Enumerated(EnumType.STRING)
    @Column(name = "claim_type", nullable = false, length = 30)
    private ClaimType claimType;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    @Builder.Default
    private ClaimStatus status = ClaimStatus.SUBMITTED;

    @Column(name = "incident_date", nullable = false)
    private LocalDate incidentDate;

    @Column(name = "incident_description", nullable = false, columnDefinition = "TEXT")
    private String incidentDescription;

    @Column(name = "incident_location", length = 300)
    private String incidentLocation;

    // ── Financial ─────────────────────────────────────────────────────────────

    /** Amount the customer is claiming */
    @Column(name = "claimed_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal claimedAmount;

    /** Amount approved by adjuster (set during review) */
    @Column(name = "approved_amount", precision = 15, scale = 2)
    private BigDecimal approvedAmount;

    /** Final amount actually paid out to customer */
    @Column(name = "settled_amount", precision = 15, scale = 2)
    private BigDecimal settledAmount;

    /** Policy coverage limit — fetched from policy-service */
    @Column(name = "coverage_limit", precision = 15, scale = 2)
    private BigDecimal coverageLimit;

    // ── Priority & severity ───────────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "priority", length = 10)
    @Builder.Default
    private Priority priority = Priority.NORMAL;

    // ── Rejection / resolution ────────────────────────────────────────────────

    @Column(name = "rejection_reason", length = 500)
    private String rejectionReason;

    @Column(name = "settlement_notes", columnDefinition = "TEXT")
    private String settlementNotes;

    // ── Dates ─────────────────────────────────────────────────────────────────

    @Column(name = "review_started_at")
    private LocalDateTime reviewStartedAt;

    @Column(name = "resolved_at")
    private LocalDateTime resolvedAt;

    @Column(name = "settled_at")
    private LocalDateTime settledAt;

    @CreationTimestamp
    @Column(name = "submitted_at", updatable = false)
    private LocalDateTime submittedAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // ── Relationships ─────────────────────────────────────────────────────────

    @OneToMany(mappedBy = "claim", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @Builder.Default
    @OrderBy("uploadedAt DESC")
    private List<ClaimDocument> documents = new ArrayList<>();

    @OneToMany(mappedBy = "claim", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @Builder.Default
    @OrderBy("createdAt DESC")
    private List<ClaimNote> notes = new ArrayList<>();

    @OneToMany(mappedBy = "claim", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @Builder.Default
    @OrderBy("changedAt DESC")
    private List<ClaimStatusHistory> statusHistory = new ArrayList<>();

    // ── Enums ─────────────────────────────────────────────────────────────────

    public enum ClaimType {
        HEALTH,           // Medical expenses
        MOTOR,            // Vehicle accident / damage
        LIFE,             // Life insurance payout
        PROPERTY,         // Home / property damage
        TRAVEL,           // Travel insurance
        PERSONAL_ACCIDENT,
        LIABILITY,
        OTHER
    }

    public enum ClaimStatus {
        SUBMITTED,        // Just filed by customer
        UNDER_REVIEW,     // Agent is reviewing
        PENDING_INFO,     // More documents needed from customer
        APPROVED,         // Approved, awaiting payment
        REJECTED,         // Denied
        SETTLED,          // Payment processed
        WITHDRAWN         // Withdrawn by customer
    }

    public enum Priority {
        LOW, NORMAL, HIGH, URGENT
    }
}
